server {
    listen 80;
    
    # ESTA ES LA CLAVE: La ruta real dentro del contenedor de NGINX
    root /usr/share/nginx/html; 
    
    index index.html;

    # 1. Regla sin caché para el Service Worker
    location ~* ^/(service-worker\.js|service-worker-assets\.js)$ {
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        expires off;
        try_files $uri =404;
    }

    # 2. Regla general para el resto de la app Blazor
    location / {
        try_files $uri $uri/ /index.html;
    }
}