// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Zenda.Infrastructure;

#nullable disable

namespace Zenda.Infrastructure.Migrations
{
    [DbContext(typeof(ZendaDbContext))]
    [Migration("20260328080653_AgregarZonaHorariaSede")]
    partial class AgregarZonaHorariaSede
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Zenda.Core.Entities.Disponibilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("HoraFin")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly>("HoraInicio")
                        .HasColumnType("time without time zone");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Disponibilidad");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Negocio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Negocios");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Prestador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<int>("DuracionTurnoMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("SedeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SedeId");

                    b.ToTable("Prestadores");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Sede", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("ZonaHorariaId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NegocioId");

                    b.ToTable("Sedes");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Turno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<string>("EmailClienteInvitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaHoraFinUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHoraInicioUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NegocioId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreClienteInvitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PrestadorId")
                        .HasColumnType("uuid");

                    b.Property<string>("TelefonoClienteInvitado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedByUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PrestadorId");

                    b.ToTable("Turnos");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Disponibilidad", b =>
                {
                    b.HasOne("Zenda.Core.Entities.Prestador", "Prestador")
                        .WithMany("Horarios")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Prestador", b =>
                {
                    b.HasOne("Zenda.Core.Entities.Sede", "Sede")
                        .WithMany("Prestadores")
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Sede", b =>
                {
                    b.HasOne("Zenda.Core.Entities.Negocio", "Negocio")
                        .WithMany("Sedes")
                        .HasForeignKey("NegocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Negocio");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Turno", b =>
                {
                    b.HasOne("Zenda.Core.Entities.Prestador", "Prestador")
                        .WithMany("Turnos")
                        .HasForeignKey("PrestadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prestador");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Negocio", b =>
                {
                    b.Navigation("Sedes");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Prestador", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("Zenda.Core.Entities.Sede", b =>
                {
                    b.Navigation("Prestadores");
                });
#pragma warning restore 612, 618
        }
    }
}
